# Generated by Django 3.0.4 on 2020-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20200508_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('activity_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='PersonalWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_website', models.CharField(max_length=50)),
                ('personal_website_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='project_decription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_title',
        ),
    ]
