# Generated by Django 3.0.4 on 2020-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20200508_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
