# Generated by Django 3.0.4 on 2020-05-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20200508_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_decription',
            new_name='project_description',
        ),
    ]
